/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BlogsRouteRouteImport } from './routes/blogs/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogsIndexRouteImport } from './routes/blogs/index'
import { Route as BlogsPostsRouteImport } from './routes/blogs/posts'
import { Route as BlogsNewRouteImport } from './routes/blogs/new'
import { Route as BlogsIdIndexRouteImport } from './routes/blogs/$id/index'
import { Route as BlogsIdEditRouteImport } from './routes/blogs/$id/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRouteRoute = BlogsRouteRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogsRouteRoute,
} as any)
const BlogsPostsRoute = BlogsPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => BlogsRouteRoute,
} as any)
const BlogsNewRoute = BlogsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BlogsRouteRoute,
} as any)
const BlogsIdIndexRoute = BlogsIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => BlogsRouteRoute,
} as any)
const BlogsIdEditRoute = BlogsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => BlogsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blogs': typeof BlogsRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/blogs/new': typeof BlogsNewRoute
  '/blogs/posts': typeof BlogsPostsRoute
  '/blogs/': typeof BlogsIndexRoute
  '/blogs/$id/edit': typeof BlogsIdEditRoute
  '/blogs/$id/': typeof BlogsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/blogs/new': typeof BlogsNewRoute
  '/blogs/posts': typeof BlogsPostsRoute
  '/blogs': typeof BlogsIndexRoute
  '/blogs/$id/edit': typeof BlogsIdEditRoute
  '/blogs/$id': typeof BlogsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blogs': typeof BlogsRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/blogs/new': typeof BlogsNewRoute
  '/blogs/posts': typeof BlogsPostsRoute
  '/blogs/': typeof BlogsIndexRoute
  '/blogs/$id/edit': typeof BlogsIdEditRoute
  '/blogs/$id/': typeof BlogsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blogs'
    | '/login'
    | '/blogs/new'
    | '/blogs/posts'
    | '/blogs/'
    | '/blogs/$id/edit'
    | '/blogs/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/blogs/new'
    | '/blogs/posts'
    | '/blogs'
    | '/blogs/$id/edit'
    | '/blogs/$id'
  id:
    | '__root__'
    | '/'
    | '/blogs'
    | '/login'
    | '/blogs/new'
    | '/blogs/posts'
    | '/blogs/'
    | '/blogs/$id/edit'
    | '/blogs/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogsRouteRoute: typeof BlogsRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof BlogsRouteRoute
    }
    '/blogs/posts': {
      id: '/blogs/posts'
      path: '/posts'
      fullPath: '/blogs/posts'
      preLoaderRoute: typeof BlogsPostsRouteImport
      parentRoute: typeof BlogsRouteRoute
    }
    '/blogs/new': {
      id: '/blogs/new'
      path: '/new'
      fullPath: '/blogs/new'
      preLoaderRoute: typeof BlogsNewRouteImport
      parentRoute: typeof BlogsRouteRoute
    }
    '/blogs/$id/': {
      id: '/blogs/$id/'
      path: '/$id'
      fullPath: '/blogs/$id/'
      preLoaderRoute: typeof BlogsIdIndexRouteImport
      parentRoute: typeof BlogsRouteRoute
    }
    '/blogs/$id/edit': {
      id: '/blogs/$id/edit'
      path: '/$id/edit'
      fullPath: '/blogs/$id/edit'
      preLoaderRoute: typeof BlogsIdEditRouteImport
      parentRoute: typeof BlogsRouteRoute
    }
  }
}

interface BlogsRouteRouteChildren {
  BlogsNewRoute: typeof BlogsNewRoute
  BlogsPostsRoute: typeof BlogsPostsRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  BlogsIdEditRoute: typeof BlogsIdEditRoute
  BlogsIdIndexRoute: typeof BlogsIdIndexRoute
}

const BlogsRouteRouteChildren: BlogsRouteRouteChildren = {
  BlogsNewRoute: BlogsNewRoute,
  BlogsPostsRoute: BlogsPostsRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  BlogsIdEditRoute: BlogsIdEditRoute,
  BlogsIdIndexRoute: BlogsIdIndexRoute,
}

const BlogsRouteRouteWithChildren = BlogsRouteRoute._addFileChildren(
  BlogsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogsRouteRoute: BlogsRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
